### ISSUE TITLE
Connector pipeline failing due to access denied

### ISSUE THREAD

**Issue by MachLearnPort** [javiersoriano/sentinelascode#1]
Hello,

I was able to get the pipeline for the rules to finish successfully, however, when I used the pipeline to enable the connectors, I am failing. Below is the error (redacted TenantID).

```
##[error]Write-Error: D:\a\_temp\a5a06053-b604-46ef-9bd6-*************.ps1:3
Line |

   3 |  . 'd:\a\1\Scripts\Scripts\EnableConnectorsAPI.ps1' -TenantId ********** …

     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

     | Unable to invoke webrequest with error message: Access denied
```

This is the connector pipeline file. It is the same as the one in the pipelines directory except with the subscription value changed to my service connection (redacted).

```
name: build and deploy Connectors
resources:
 pipelines:
   - pipeline: Scripts
     source: 'scriptsCI'
trigger:
 paths:
   include:
     - Connectors/*

stages:
- stage: build_connectors

  jobs:
    - job: AgentJob
      pool:
       name: Azure Pipelines
       vmImage: 'vs2017-win2016'
      steps:
       - task: CopyFiles@2
         displayName: 'Copy Connectors'
         inputs:
          SourceFolder: Connectors
          TargetFolder: '$(Pipeline.Workspace)'

       - task: PublishBuildArtifacts@1
         displayName: 'Publish Artifact: ConnectorsFile'
         inputs:
          PathtoPublish: '$(Pipeline.Workspace)'
          ArtifactName: ConnectorsFile

- stage: deploy_connectors
  jobs:
    - job: AgentJob
      pool:
       name: Azure Pipelines
       vmImage: 'windows-2019'
      variables: 
      - group: Az connection settings
      steps:
      - download: current
        artifact: ConnectorsFile
      - download: Scripts
        patterns: '*.ps1'
      - task: AzurePowerShell@4
        displayName: 'Create and Update Connectors'
        inputs:
         azureSubscription: '************************'
         ScriptPath: '$(Pipeline.Workspace)/Scripts/Scripts/EnableConnectorsAPI.ps1'
         ScriptArguments: '-TenantId $(TenantId) -ClientId $(ClientId) -ClientSecret $(ClientSecret) -SubscriptionId $(SubscriptionId) -ResourceGroup $(ResourceGroup) -Workspace $(Workspace) -ConnectorsFile connectors.json'
         azurePowerShellVersion: LatestVersion
         pwsh: true
```

I am not sure why it is failing (inadequate permissions for the service connection?). Please advise. 

Cheers.
